--------------------------------------------------------------------------------
Configuration
--------------------------------------------------------------------------------
host
 trace A (shutdown_reset.strace.client)
 trace B (shutdown_reset.strace.server)

--------------------------------------------------------------------------------
Verifying Traces
--------------------------------------------------------------------------------

No valid action:
[Error] trace B: ('accept_syscall', (0, '127.0.0.1', 42885), (1, None))
   => NO_PENDING_CONN: There are no pending connections.
[Error] trace A: ('connect_syscall', (1, '127.0.0.1', 55051), (0, None))
   => ECONNREFUSED: [Ambiguous Misbehavior]                The target address was not listening for connections or refused the connection request.

--------------------------------------------------------------------------------
Network Configuration Issues
--------------------------------------------------------------------------------
TCP server socket B0 (private address 127.0.0.1:36615) failed to find corresponding connects for 1 accept(s)
 * There are 1 unmatched accepts from IP 127.0.0.1
 * Trace B may be behind a NAT and port forwarding may be occurring

Trace A failed to connect to 127.0.0.1:55051 1 time(s) because the connection was refused

Please check if there are any NATs present which are not explicitly declared in the configuration file
 * If so, add them to configuration file and rerun NetCheck

--------------------------------------------------------------------------------
Possible Problems Detected
--------------------------------------------------------------------------------
 * The model failed to process the entire trace
 * There may be one or more NATs not declared in the configuration file

For more details, adjust the variables defined in trace_output.py and posix_output.py to change the level of output
